version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000 
    working_dir: /app
    volumes: 
      - ./:/app
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: weather
      OPEN_WEATHER_API_KEY: 655dfc390726be35679ee1f171b45301

  # back:
  #   image: node:12-alpine
  #   command: sh -c "npm run react-dev"
  #   working_dir: /app
  #   ports: 
  #     - 8080:8080
  #   volumes: 
  #     - ./:/app
  
  mysql:
    image: mysql:5.7
    volumes:
       - weather-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: weather

volumes:
  weather-mysql-data:




